### ISSUE TITLE
Internet connection sharing should specify where the bb.sh script should run

### ISSUE THREAD

**Issue by rothgar** [hak5/bashbunny-wiki#4]
The wiki mentions to run the bb.sh script to share internet with the bash bunny but it doesn't say if you should try to run that script on the bash bunny via transferring the file and connecting via serial or if you are supposed to run it on the host OS.

I realize it may sound obvious to run it on the host but I think clarification would be helpful.

**Comment by rothgar** [comment]
It also would be helpful to say what mode the bash bunny should be in to share connection. Should it be in arming mode, serial, or one of the network attack modes.

**Comment by sebkinne** [comment]
@rothgar I'd be stoked if you sent a PR our way :)
