### ISSUE TITLE
switch issue

### ISSUE THREAD

**Issue by ACEALL** [hak5/bashbunny-wiki#6]
Don't know if its a software or hardware issue 
Just got the bunny today loading in simple Quack payloads as basic tests 
Sometimes switch 1 will not work it mounts and just sits there then i copy and paste the payloads to switch 2 then it works perfect then without editing anything else switch to the first one and it works perfect just the same.

**Comment by sebkinne** [comment]
@ACEALL this could be a defective device or bad payload. Please post this to the forums for help :)
